version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14

    commands:
      - node --version
      - npm --version

  build:
    commands:
      - cd /codebuild/output/src858187716/src
      - ls -al  # List files to verify you're in the right directory
      - npm install
      - npm run build
