version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14

    commands:
      - node --version
      - npm --version

  build:
    commands:
      - cd /codebuild/output/src2299962806/src  # Navigate to your project directory
      - ls -al  # Verify files in the directory
      - npm install
      - npm run build
