version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the project..."
      - cd $CODEBUILD_SRC_DIR  # Navigate to the root directory of your source code
      - npm run build  # Example build command

artifacts:
  files:
    - '**/*'
