version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Build started on `date`
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
