version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14

    commands:
      - node --version
      - npm --version

  build:
    commands:
      - cd src  # Assuming 'src' is the directory where your project resides
      - ls -al  # List files to verify you're in the right directory
      - npm install
      - npm run build
